[package]
name = "registry_loader"
version = "0.1.0"
edition = "2024"

[dependencies]
winapi = { version = "0.3", features = ["winreg", "heapapi", "winerror", "processthreadsapi", "memoryapi", "winnt", "synchapi", "winbase"] }